version: '3.8'

services:
  kaitai-webide-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

